### ISSUE TITLE
Pause and Stop functions

### ISSUE THREAD

**Issue by Francisc** [jcowgar/sublime-task-timer#1]
Hello,

This is a nice idea, but it should have Pause and Stop commands.
Pausing for when you take a break, talk to someone etc.
Stop when you don't want the timer running. You currently have to close ST to stop the timer.

An option to see time in status bar at all time would also be nice, but not crucial.
Should be optional though, I don't want to see time pass all the time, bad for coding.

**Comment by jcowgar** [comment]
Pause would be handy, complicates coding, but not terribly. I can add a stop in there as well, but when you are not accessing any of the timer functions, nothing is running, so there is no performance hit for having a timer running. It simply stores a variable of when the timer started and when you check the status it does date math to determine the current date/time vs. when you hit the start button.

As for the time in the status bar, I will work on getting pause/stop functioning first and then dig into how to update the status bar as an option.

**Comment by jcowgar** [comment]
I have added pause and stop commands. The elapsed time is displayed on both as well as when checking the timer status of course. Please check out the new functionality and report back if it is working to your expectations.  If not I'll reopen the task.

Thank you very much for the suggestion, it is much nicer now because of it.
